tatfook/wikicraft

- r_package.js
> package fixed

- www/wiki/html/header.html
- www/wiki/html/newWebsite.html
- www/wiki/js/app/controller/headerController.js
- www/wiki/js/app/controller/newWebsiteController.js
[issue 720](https://github.com/tatfook/wikicraft/issues/720)
[issue 721](https://github.com/tatfook/wikicraft/issues/721)
> issue #720、 issue 721

- .gitignore
- test.sh
- www/wiki/html/templates/blank_theme.md
- www/wiki/js/mod/template/js/default.js
added a new property for default theme
```@template/js/default
{
"class": "container",
"footerpage":"_bottom"
}
```
> Default theme

- www/wiki/html/header.html
> hotfix: remove header paracraft for icp.

- www/wiki/js/mod/board/main.js
this is a demo of hotfix. But it does fix an issue
> hotfix: board not show up on first time use

- www/wiki/models/bigfile.page
目前bigfile分支功能测试通过，现合并入release分支
> bigfile delete fixed

- www/wiki/js/mod/board/main.js
> update diagram menu

- www/wiki/js/mod/board/main.html
- www/wiki/js/mod/board/main.js
> update diagram modal size

- www/wiki/js/app/controller/payController.js
- www/wiki/models/pay.page
> pay limit less 1000 yuan

- www/wiki/html/editWebsite.html
- www/wiki/html/footer.html
- www/wiki/html/newWebsite.html
- www/wiki/html/services.html
- www/wiki/html/statics.html
- www/wiki/html/user.html
- www/wiki/html/userProfile.html
- www/wiki/html/website.html
- www/wiki/js/app/controller/bigfileController.js
- www/wiki/js/app/controller/mainController.js
- www/wiki/js/app/controller/newWebsiteController.js
- www/wiki/js/mod/wiki/html/siteSubmitWorks.html
> style for phone

- www/wiki/models/oauth_app.page
> hotfix: fix_getTokenByCode

- www/wiki/js/mod/admin/js/index.js
- www/wiki/models/oauth_app.page
> fix: Fix oauth

- www/wiki/html/editWebsite.html
- www/wiki/js/app/controller/bigfileController.js
- www/wiki/js/app/controller/editWebsiteController.js
- www/wiki/js/app/factory/gitlab.js
- www/wiki/models/data_upgrade.page
- www/wiki/models/group_user.page
- www/wiki/models/qiniu.page
- www/wiki/models/site_group.page
- www/wiki/models/site_user.page
帮吴香安rebase下代码，将group功能相关提交pick到master上来，作为hotfix
> Rebase group

- www/wiki/js/app/controller/payController.js
- www/wiki/models/pay.page
> hotfix: money quota

- www/wiki/js/mod/entries/html/entries.html
- www/wiki/js/mod/entries/js/entries.js
> 生成章节的全部改为我们这边生成

- www/wiki/models/user.page
`if params.bind then` causes unbinding failed.
params.bind == false is for unbinding as the former logic
> hotfix phone unbind

- www/wiki/js/mod/wiki/html/worldList.html
- www/wiki/mod/worldshare/models/worlds.page
> fix: world list link

- www/wiki/html/editWebsite.html
- www/wiki/js/app/controller/editWebsiteController.js
- www/wiki/js/app/controller/mainController.js
- www/wiki/js/app/helper/util.js
- www/wiki/models/website.page
> feat(setting defaultpage) :增加可自定义默认首页功能 #676

- www/wiki/js/mod/admin/html/index.html
- www/wiki/js/mod/admin/js/index.js
- www/wiki/models/pay.page
- Fix admin index js
- Tab to 4 spaces
> Fix admin index js

- www/wiki/html/editWebsite.html
- www/wiki/js/app/controller/editWebsiteController.js
> fix:default page url cant be set in chinese

- www/wiki/html/editWebsite.html
- www/wiki/js/app/controller/editWebsiteController.js
- www/wiki/js/app/controller/mainController.js
- www/wiki/js/app/helper/util.js
- www/wiki/models/website.page
> Revert defaultpage

- www/wiki/js/mod/adi/html/title.html
- www/wiki/js/mod/adi/js/title.js
> update title mod

- www/wiki/js/mod/adi/html/pictureText.html
- www/wiki/js/mod/adi/js/pictureText.js
> fix picture text

- www/wiki/js/mod/adi/html/text.html
- www/wiki/js/mod/adi/js/text.js
> text_mod v1

- www/wiki/js/app/controller/mainController.js
- www/wiki/js/app/controller/moduleEditorController.js
- www/wiki/js/app/factory/selfDefinedModal.js
- www/wiki/js/app/preload.js
- www/wiki/js/mod/adi/html/board.html
- www/wiki/js/mod/adi/js/board.js
- www/wiki/js/mod/board/main.js
> adi board mod

- www/wiki/js/mod/adi/html/comment.html
- www/wiki/js/mod/adi/js/comment.js
> Comment mod

- www/wiki/js/mod/adi/js/comment.js
fix style preview picture path
> fix style preview picture path

- www/wiki/js/mod/adi/html/text.html
- www/wiki/js/mod/adi/js/text.js
> Text mod add container class

- www/wiki/js/mod/adi/html/comment.html
- www/wiki/js/mod/adi/js/comment.js
> add container class

- www/wiki/js/mod/adi/html/menu.html
- www/wiki/js/mod/adi/html/text.html
> menu_mod add container class

- www/wiki/js/mod/adi/html/comment.html
- www/wiki/js/mod/adi/js/comment.js
> fix title name

- www/wiki/js/mod/adi/html/text.html
- www/wiki/js/mod/adi/js/text.js
> add <a> link

- www/wiki/js/mod/adi/html/text.html
- www/wiki/js/mod/adi/js/text.js
> text_mod fix href

- www/wiki/js/mod/adi/html/comment.html
- www/wiki/js/mod/adi/js/comment.js
comment_mod fix open/shutup switch
> comment_mod fix open/shutup switch

- www/wiki/js/mod/adi/html/text.html
> add {{ }} to ng-href

- www/wiki/js/mod/adi/html/text.html
fix proMode mod-container active problem
> fix proMode mod-container active problem

- www/wiki/js/app/controller/moduleEditorController.js
- www/wiki/js/app/helper/markdownwiki.js
[issue #1269 ](https://github.com/tatfook/wikicraft/issues/1269)
[issue #1268 ](https://github.com/tatfook/wikicraft/issues/1268)
> Fix view addicon

- www/wiki/js/mod/adi/html/paracraft.html
- www/wiki/js/mod/adi/js/paracraft.js
> fix paracraft style

- www/wiki/js/mod/adi/html/text.html
- www/wiki/js/mod/adi/js/text.js
> add MD 2 HTML

- www/wiki/js/mod/adi/js/project.js
project_mod add MD 2 HTML trans
> project_mod add MD 2 HTML trans

- www/wiki/js/mod/adi/html/text.html
- www/wiki/js/mod/adi/js/text.js
> fixed multi_text href

- www/wiki/js/mod/adi/html/img.html
> update  background

- www/wiki/js/mod/adi/html/menu.html
- www/wiki/js/mod/adi/html/text.html
> fix style2 title problem

- www/wiki/js/mod/adi/html/title.html
> fix title drop problem

- www/wiki/js/mod/adi/js/title.js
change style preview picture path
> change style preview picture path

- www/wiki/js/mod/adi/html/project.html
> update project style

- www/wiki/js/mod/adi/html/paracraft.html
- www/wiki/js/mod/adi/js/paracraft.js
> update paracraft style

- www/wiki/js/mod/adi/html/paracraft.html
> add click event

- www/wiki/js/mod/admin/js/index.js
- www/wiki/models/wiki_module.page
fix wikicmd modify wikicmdname
> fix wikicmd modify wikicmdname

- www/wiki/js/mod/adi/js/paracraft.js
> update multi text desc

- www/wiki/js/mod/adi/js/comment.js
editorMode also can preview comment content
> editorMode also can preview comment content

- www/wiki/js/mod/adi/html/comment.html
- www/wiki/js/mod/adi/js/comment.js
> eComment mod

- www/wiki/js/mod/adi/html/project.html
- www/wiki/js/mod/adi/js/project.js
> fix multi text

- www/wiki/models/vip.page
> Hot fix vip payhook ip

- www/wiki/models/vip.page
> update server ip

- www/wiki/js/mod/adi/html/permissions.html
- www/wiki/js/mod/adi/js/permissions.js
> Vip permissions

- www/wiki/js/mod/adi/js/permissions.js
> update adi vip permission

- www/wiki/js/mod/adi/js/img_loop.js
> Carousel mod

- www/wiki/js/mod/adi/html/mix_position.html
- www/wiki/js/mod/adi/html/vipread.html
- www/wiki/js/mod/adi/js/mix_position.js
- www/wiki/js/mod/adi/js/vipread.js
> rename 2 module

- www/wiki/js/mod/adi/html/richText.html
- www/wiki/js/mod/adi/js/richText.js
> new richtext

- www/wiki/js/mod/adi/html/vipread.html
- www/wiki/js/mod/adi/js/vipread.js
> update adi vipread

- www/wiki/js/mod/adi/html/mix_layer.html
- www/wiki/js/mod/adi/js/mix_layer.js
> Mix layer mod

- www/wiki/js/mod/adi/html/qq.html
> adi QQ renew

- www/wiki/js/mod/adi/html/vipread.html
- www/wiki/js/mod/adi/js/vipread.js
> update adi vip

- www/wiki/html/moduleEditor.html
- www/wiki/js/app/controller/moduleEditorController.js
> update editor style

- www/wiki/js/mod/adi/html/qq.html
> repair qq-mod

- www/wiki/js/mod/adi/html/vipread.html
> update vip adi style

- www/wiki/models/page_code.page
> add page_code

- www/wiki/js/mod/adi/js/richText.js
> fix update bug

- www/wiki/js/mod/adi/js/richText.js
> rich text video display

- www/wiki/js/mod/adi/html/qq.html
- www/wiki/js/mod/adi/js/qq.js
- www/wiki/js/mod/adi/js/richText.js
> Fix update bug for qq

- www/wiki/js/mod/adi/html/title.html
> fix title bug

- www/wiki/js/mod/adi/js/richText.js
> fix rich text

- www/wiki/js/app/controller/wikiEditorController.js
> Annotated code

- www/wiki/js/mod/adi/html/paracraft.html
> fix paracraft bug

- www/wiki/js/mod/adi/html/text.html
> fix text bug

- www/wiki/js/mod/board/main.js
> fix board bug

- www/wiki/js/mod/adi/html/vipread.html
- www/wiki/js/mod/adi/js/vipread.js
> fix vip read

- www/wiki/js/mod/adi/html/paracraft.html
> fix-paracraft

- www/wiki/js/mod/adi/html/img_loop.html
> phone carousel

- www/wiki/js/app/controller/payController.js
- www/wiki/models/pay.page
> test wechat pay

- www/wiki/models/website.page
> fix get websites by username

- www/wiki/auth/github.page
- www/wiki/auth/qq.page
- www/wiki/auth/weixin.page
- www/wiki/auth/xinlangweibo.page
- www/wiki/helpers/index.page
- www/wiki/helpers/sms.page
- www/wiki/js/app/config.js
- www/wiki/js/app/factory/gitlab.js
- www/wiki/models/data_source.page
- www/wiki/models/elasticsearch.page
- www/wiki/models/oauth_app.page
- www/wiki/models/pay.page
- www/wiki/models/qiniu.page
- www/wiki/models/util.page
> Feature env

- www/wiki/js/app/helper/util.js
- www/wiki/js/mod/profile/html/modalTemplate/addCertificationsModal.html
- www/wiki/js/mod/profile/html/modalTemplate/addExperienceModal.html
- www/wiki/js/mod/profile/js/certifications.js
- www/wiki/js/mod/profile/js/experiences.js
> 个人成长系统加入时间控件

- www/wiki/js/mod/profile/html/modalTemplate/addWorkModal.html
- www/wiki/js/mod/profile/js/works.js
#	www/wiki/js/mod/profile/html/works.html
#	www/wiki/js/mod/profile/js/works.js
> 添加作品、作品展示fix

- www/wiki/helpers/index.page
- www/wiki/html/search.html
- www/wiki/js/app/controller/searchController.js
- www/wiki/js/app/controller/wikiEditorController.js
- www/wiki/models/elasticsearch.page
- www/wiki/models/pages.page
- www/wiki/models/skills.page
- www/wiki/models/tags.page
- www/wiki/models/user.page
- www/wiki/models/user_fans.page
- www/wiki/models/website.page
search service based on elasticsearch
> Search service

- www/wiki/models/pages_stars.page
remove test code in pages_stars
> remove test code in pages_stars

- www/wiki/models/pages.page
> fix pages model

- www/wiki/js/app/controller/payController.js
> fix-pay-success

- www/wiki/models/pages.page
- www/wiki/models/pages_stars.page
> fix-starred-pages-list

- www/wiki/models/elasticsearch.page
- www/wiki/models/pages.page
fix search results of own pages
> fix search results of own pages

- www/wiki/models/user.page
- www/wiki/models/util.page
> set test sms code

- www/wiki/js/mod/adi/html/paracraft.html
- www/wiki/js/mod/adi/js/paracraft.js
paracraft mod selfdefined desc
> paracraft mod selfdefined desc

- www/wiki/models/errors.page
- www/wiki/models/pages.page
- www/wiki/models/pages_stars.page
- www/wiki/models/skills.page
- www/wiki/models/util.page
- www/wiki/models/validators.page
> fix api permissions

- www/wiki/js/mod/adi/js/paracraft.js
> fix paracraft convert data

- www/wiki/models/util.page
> remove debug logs

- www/wiki/js/mod/adi/html/mix_layer.html
- www/wiki/js/mod/adi/html/paracraft.html
- www/wiki/js/mod/wiki/html/bigfile.html
- www/wiki/js/mod/wiki/html/video.html
1. remove mix layer container
2. remove bigfile container
3. pracraft mod style
> 1. remove mix layer container 2. remove bigfile container 3. pracraft mod style

- www/wiki/js/mod/board/main.js
> Fix board params update

- www/wiki/js/mod/adi/html/mix_layer.html
- www/wiki/js/mod/adi/html/paracraft.html
- www/wiki/js/mod/adi/js/paracraft.js
- www/wiki/js/mod/wiki/html/bigfile.html
- www/wiki/js/mod/wiki/html/video.html
> Merge from master

- www/wiki/js/mod/adi/html/paracraft.html
> fix paracraft download notice

- www/wiki/models/pages.page
add an api to migrate markdown files from git into elasticsearch
> migrate md

- www/wiki/models/pages.page
> update migrate md api

- www/wiki/models/pages.page
> fix migrate md

- www/wiki/models/pages.page
fix error condition in migrate_one
> fix error condition in migrate_one

- www/wiki/js/mod/adi/js/paracraft.js
> paracraft protocol updated

- www/wiki/models/pages.page
> Fix a bug in updateVisitCount

- www/wiki/mod/worldshare/models/worlds.page
world share worlds api updated
> world share worlds api updated

- www/wiki/mod/worldshare/models/worlds.page
rename api getWorldByName -> getWorldByIdWithName
> rename api getWorldByName -> getWorldByIdWithName

- www/wiki/mod/worldshare/models/worlds.page
> add getWorldByFilePath api

- www/wiki/mod/worldshare/models/worlds.page
> fix worlds api

- www/wiki/html/join.html
- www/wiki/html/login.html
- www/wiki/js/app/controller/joinController.js
- www/wiki/js/app/controller/loginController.js
- www/wiki/js/app/helper/translationsTable.js
> fix login placeholder

- www/wiki/html/header.html
- www/wiki/html/home.html
- www/wiki/js/app/controller/appsController.js
- www/wiki/js/app/controller/headerController.js
- www/wiki/js/app/controller/homeController.js
- www/wiki/js/app/controller/servicesController.js
- www/wiki/js/app/controller/userCenterController.js
- www/wiki/js/app/helper/translationsTable.js
update
update translation
hide VIP
hide vip for i18n
> hide iicc for global version

- www/wiki/html/newWebsite.html
- www/wiki/js/app/controller/newWebsiteController.js
- www/wiki/js/app/factory/account.js
- www/wiki/js/app/helper/translationsTable.js
> fix new website i18n

- www/wiki/html/bigfile.html
- www/wiki/html/dataSource.html
- www/wiki/js/app/controller/bigfileController.js
- www/wiki/js/app/controller/homeController.js
- www/wiki/js/app/controller/searchController.js
- www/wiki/js/app/controller/userController - 副本.js
- www/wiki/js/app/controller/userController.js
- www/wiki/js/app/controller/userProfileController.js
- www/wiki/js/app/helper/translationsTable.js
- www/wiki/js/mod/profile/html/headerinfo.html
- www/wiki/js/mod/profile/js/activities.js
- www/wiki/js/mod/profile/js/followUser.js
- www/wiki/js/mod/profile/js/headerinfo.js
- www/wiki/js/mod/profile/js/sites.js
- www/wiki/js/mod/wiki/js/header.js
> update a lot of translation

- www/wiki/js/app.js
- www/wiki/js/app/controller/homeController.js
- www/wiki/js/app/controller/joinController.js
- www/wiki/js/app/controller/loginController.js
- www/wiki/js/app/helper/storage.js
> reverse change

- www/wiki/auth/facebook.page
- www/wiki/auth/google.page
- www/wiki/auth/qq.page
- www/wiki/auth/weixin.page
- www/wiki/auth/xinlangweibo.page
- www/wiki/html/search.html
- www/wiki/html/userProfile.html
- www/wiki/html/wikiBlock.html
- www/wiki/js/mod/admin/html/browser.html
- www/wiki/js/mod/admin/html/index.html
- www/wiki/js/mod/wiki/html/siteMemberManage.html
- www/wiki/js/mod/wiki/html/siteWorksManage.html
- www/wiki/js/mod/wiki/html/workslist.html
- www/wiki/mod/modelshare/html/index.html
fix cannot login after unbind
fix uib-pagination
> Fix usernotbindnodata

- www/wiki/html/services.html
- www/wiki/js/app/controller/servicesController.js
> fix vip deadline
